In [1]:
import numpy as np

使用np.arange()生成整数递增序列

In [2]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# 包含1，不包含10，步长为2
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [4]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [5]:
np.linspace(1,10,10,endpoint=False)

array([1. , 1.9, 2.8, 3.7, 4.6, 5.5, 6.4, 7.3, 8.2, 9.1])

%time 计算代码执行时间，代码只执行一次，并且需要放在一行

In [6]:
arr = np.arange(10000)
%time for i in range(10000): arr**2

Wall time: 111 ms


%timeit 计算代码执行的时间，代码会重复执行多次并计算平均值，并且需要放在一行

In [7]:
# for循环冒号后面不换行也是可以的
%timeit for i in range(10000): arr*2

92.8 ms ± 3.38 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


datetime.datatime.now()获取程序开始和结束的时间

In [8]:
import datetime
start = datetime.datetime.now()
arr = np.arange(10000)
for i in range(10000):
    arr**2
end = datetime.datetime.now()
print('start time:{}'.format(start))
print('end time:{}'.format(end))
print(end - start)

start time:2020-01-31 22:40:40.750290
end time:2020-01-31 22:40:40.857225
0:00:00.106935


time.time()获取程序开始和结束的时间

In [9]:
import time
import datetime
start = time.time()
arr = np.arange(10000)
for i in range(10000):
    arr**2
end = time.time()
print('start time:{}'.format(start))
print('end time:{}'.format(end))
print(end - start)

start time:1580481640.865222
end time:1580481641.0031424
0.13792037963867188


timeit.timeit('',number=10000)计算''之间代码执行的时间
单引号之内只能执行赋值的操作？

In [10]:
import timeit
timeit.timeit('arr = [1,2,3,4]',number=10000)

0.0011521999999999366

生成ndarray对象的方式有哪些？  
np.array()  
np.zeros()  
np.ones()  
np.arange()  
np.random.randint()  
np.random.randn()  
np.random.rand()  
np.random.random()  
np.linspace()

In [11]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.ones(3)

array([1., 1., 1.])

In [15]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
# 第一个参数表示开始值，第二个参数表示结束值（不包含），第三个参数表示矩阵的shape
np.random.randint(2,5,3)

array([3, 4, 4])

In [17]:
np.random.randint(1,10,(2,3))

array([[1, 2, 3],
       [9, 9, 8]])

In [18]:
# 标准正态分布随机数
np.random.randn(2,3)

array([[-0.33693468, -0.96424677,  1.24618222],
       [-1.24512893, -0.46048994,  1.13214947]])

In [19]:
# 0-1之间随机分布数
np.random.rand(2,3)

array([[0.20391066, 0.96361845, 0.34924766],
       [0.86520897, 0.27986869, 0.45536388]])

In [20]:
# # 0-1之间随机分布数
np.random.random((2,3))

array([[0.12488397, 0.27091393, 0.90156315],
       [0.31959294, 0.13031608, 0.94489324]])

reshape方法用于转换矩阵的形状

In [21]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [22]:
# 生成二维数组，列为1
arr = np.arange(9).reshape(-1,1)
print(arr.shape)
print(arr)

(9, 1)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [23]:
# 生成二维数组，行为1
arr = np.arange(9).reshape(1,-1)
print(arr.shape)
print(arr)

(1, 9)
[[0 1 2 3 4 5 6 7 8]]


reshape(-1,n)将原数组转换成列为n的数组，行自行计算。数组元素的个数需要能够被n整除。

In [24]:
arr = np.arange(12).reshape(-1,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

reshape(n,-1)将原数组转换成行为n的数组，列自行计算。数组元素的个数需要能够被n整除。

In [25]:
arr = np.arange(12).reshape(3,-1)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

ndarray对象之间进行加减乘除的规则

In [26]:
arr1 = np.random.randint(1,20,9).reshape(3,3)
arr1

array([[ 6, 15, 18],
       [15,  6, 13],
       [ 8, 11, 13]])

In [27]:
arr1 + 1

array([[ 7, 16, 19],
       [16,  7, 14],
       [ 9, 12, 14]])

In [28]:
arr1 * 2

array([[12, 30, 36],
       [30, 12, 26],
       [16, 22, 26]])

In [29]:
arr2 = np.random.rand(9).reshape(3,3)
arr2

array([[0.53144021, 0.45760878, 0.3522288 ],
       [0.0908692 , 0.37956808, 0.47126566],
       [0.89050228, 0.42693104, 0.36052497]])

In [30]:
arr1 + arr2

array([[ 6.53144021, 15.45760878, 18.3522288 ],
       [15.0908692 ,  6.37956808, 13.47126566],
       [ 8.89050228, 11.42693104, 13.36052497]])

In [31]:
arr1 - arr2

array([[ 5.46855979, 14.54239122, 17.6477712 ],
       [14.9091308 ,  5.62043192, 12.52873434],
       [ 7.10949772, 10.57306896, 12.63947503]])

两个数组相同位置的元素进行相乘

In [32]:
arr1 = np.random.rand(3,3)
arr2 = np.random.rand(3,3)

In [33]:
arr1

array([[0.81687648, 0.01116792, 0.23988315],
       [0.06062074, 0.60960185, 0.82635559],
       [0.14615853, 0.93044997, 0.17281389]])

In [34]:
arr2

array([[0.53111321, 0.29169344, 0.0409609 ],
       [0.76591749, 0.46171739, 0.24020159],
       [0.75267544, 0.46290635, 0.05309881]])

In [35]:
arr1 * arr2

array([[0.43385389, 0.00325761, 0.00982583],
       [0.04643048, 0.28146377, 0.19849193],
       [0.11000994, 0.4307112 , 0.00917621]])

计算两个矩阵的点积（内积）

In [36]:
# 点乘，arr1的列数等于arr2的行数
arr1.dot(arr2)

array([[0.62296175, 0.35447737, 0.04888006],
       [1.12107875, 0.68167169, 0.19278892],
       [0.9203474 , 0.55223506, 0.23865856]])

In [37]:
np.dot(arr1,arr2)

array([[0.62296175, 0.35447737, 0.04888006],
       [1.12107875, 0.68167169, 0.19278892],
       [0.9203474 , 0.55223506, 0.23865856]])

In [38]:
arr1 / arr2

array([[1.53804588, 0.03828649, 5.85639321],
       [0.07914787, 1.32029215, 3.44025858],
       [0.19418534, 2.01001775, 3.25457151]])

两个数组进行比较会生成布尔数组

In [39]:
arr1 = np.random.rand(9).reshape(3,3)
arr1

array([[0.33695403, 0.35069537, 0.18504994],
       [0.33374968, 0.38206546, 0.95494442],
       [0.61739398, 0.67562544, 0.60528098]])

In [40]:
arr2 = np.random.rand(9).reshape(3,3)
arr2

array([[0.43242737, 0.38173394, 0.57802072],
       [0.82846985, 0.91816669, 0.10845464],
       [0.99507329, 0.53545276, 0.45662288]])

In [41]:
arr1 > arr2

array([[False, False, False],
       [False, False,  True],
       [False,  True,  True]])

shape属性表示数组的形状
ndim属性表示数组的维度

In [42]:
print(arr1.shape)
print(arr1.ndim)

(3, 3)
2


In [43]:
arr1 = np.arange(3)
print(arr1.shape)
print(arr1.ndim)

(3,)
1


In [44]:
arr1 = np.array([[1,2,3]])
print(arr1.shape)
print(arr1.ndim)

(1, 3)
2


In [45]:
arr1 = np.array([[1],[2],[3]])
print(arr1.shape)
print(arr1.ndim)

(3, 1)
2


dtype属性表示数组的数据类型

In [46]:
arr = np.arange(9).reshape(3,3)
arr.dtype

dtype('int32')

In [47]:
arr = np.random.rand(3,3)
arr.dtype

dtype('float64')

In [48]:
arr = np.array([['helloo','world'],['this','is']])
arr.dtype

dtype('<U6')

In [49]:
arr = np.array([True,False,True,True])
arr.dtype

dtype('bool')

使用astype方法进行数据类型转换

In [50]:
arr = np.array([True,False,True,True]).astype(int)
print(arr)
print(arr.dtype)

[1 0 1 1]
int32


In [51]:
arr = arr.astype(float)
print(arr)
print(arr.dtype)

[1. 0. 1. 1.]
float64


计算次方和开方

In [52]:
arr = np.arange(4)
print(arr**2)
print(np.power(arr,2))
print(np.square(arr))

[0 1 4 9]
[0 1 4 9]
[0 1 4 9]


In [53]:
print(arr**0.5)
print(np.power(arr,0.5))
print(np.sqrt(arr))

[0.         1.         1.41421356 1.73205081]
[0.         1.         1.41421356 1.73205081]
[0.         1.         1.41421356 1.73205081]


数组的索引

In [54]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [55]:
arr[2]

array([6, 7, 8])

In [56]:
arr[2][1]

7

In [57]:
arr[2,1]

7

数组的切片，包含冒号左边的数字，不包含右边的数字。

In [58]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [59]:
arr[0:1]

array([[0, 1, 2]])

In [60]:
arr[1:3]

array([[3, 4, 5],
       [6, 7, 8]])

In [61]:
arr[0:2,1:3]

array([[1, 2],
       [4, 5]])

对切片的修改，会反映到原始数组上

In [62]:
arr[0:1,2] = 4
arr

array([[0, 1, 4],
       [3, 4, 5],
       [6, 7, 8]])

使用copy()方法进行复制，再进行修改，则不影响原始数组

In [63]:
arr1 = arr[0:1].copy()
arr1

array([[0, 1, 4]])

In [64]:
arr1[0,1] = 2
arr1

array([[0, 2, 4]])

In [65]:
arr

array([[0, 1, 4],
       [3, 4, 5],
       [6, 7, 8]])

什么是切片索引？将切片与索引同时使用，可以得到低纬度的数组。

In [66]:
arr[0:2,2]

array([4, 5])

如何使用布尔索引？

In [67]:
arr = np.random.randint(1,100,(4,3))
arr

array([[84, 85, 23],
       [34, 80, 16],
       [11, 10, 74],
       [82, 56, 95]])

In [68]:
arr[:,2] > 30

array([False, False,  True,  True])

In [69]:
arr[arr[:,2] > 30]

array([[11, 10, 74],
       [82, 56, 95]])

In [70]:
arr[2,:] > 30

array([False, False,  True])

In [71]:
arr[:,arr[2,:] > 30]

array([[23],
       [16],
       [74],
       [95]])

如何使用神奇索引？  
所谓的神奇索引，就是使用整数列表来对原数组进行排序，或者选取想要的行数。

In [72]:
arr

array([[84, 85, 23],
       [34, 80, 16],
       [11, 10, 74],
       [82, 56, 95]])

In [73]:
arr[[2,1,0,3]]

array([[11, 10, 74],
       [34, 80, 16],
       [84, 85, 23],
       [82, 56, 95]])

In [74]:
arr[:,[2,1,0]]

array([[23, 85, 84],
       [16, 80, 34],
       [74, 10, 11],
       [95, 56, 82]])

In [75]:
arr

array([[84, 85, 23],
       [34, 80, 16],
       [11, 10, 74],
       [82, 56, 95]])

数组的转置

In [76]:
arr.T

array([[84, 34, 11, 82],
       [85, 80, 10, 56],
       [23, 16, 74, 95]])

常用的一元通用函数

In [77]:
arr

array([[84, 85, 23],
       [34, 80, 16],
       [11, 10, 74],
       [82, 56, 95]])

In [78]:
# 求平方根
np.sqrt(arr)

array([[9.16515139, 9.21954446, 4.79583152],
       [5.83095189, 8.94427191, 4.        ],
       [3.31662479, 3.16227766, 8.60232527],
       [9.05538514, 7.48331477, 9.74679434]])

In [79]:
# 求平方
np.square(arr)

array([[7056, 7225,  529],
       [1156, 6400,  256],
       [ 121,  100, 5476],
       [6724, 3136, 9025]], dtype=int32)

In [80]:
# 求e为底的结果
np.exp(arr)

array([[3.02507732e+36, 8.22301271e+36, 9.74480345e+09],
       [5.83461743e+14, 5.54062238e+34, 8.88611052e+06],
       [5.98741417e+04, 2.20264658e+04, 1.37338298e+32],
       [4.09399696e+35, 2.09165950e+24, 1.81123908e+41]])

In [81]:
arr = arr * -1
arr

array([[-84, -85, -23],
       [-34, -80, -16],
       [-11, -10, -74],
       [-82, -56, -95]])

求绝对值

In [82]:
np.abs(arr)

array([[84, 85, 23],
       [34, 80, 16],
       [11, 10, 74],
       [82, 56, 95]])

In [83]:
np.fabs(arr)

array([[84., 85., 23.],
       [34., 80., 16.],
       [11., 10., 74.],
       [82., 56., 95.]])

In [84]:
# np.modf()返回小数部分和整数部分
arr = np.random.rand(3,3)
arr

array([[0.32880543, 0.52410346, 0.08043142],
       [0.7105371 , 0.0826245 , 0.29709063],
       [0.13284273, 0.66635215, 0.9687638 ]])

In [85]:
arr = arr * 3
arr

array([[0.98641629, 1.57231039, 0.24129427],
       [2.13161129, 0.2478735 , 0.89127189],
       [0.3985282 , 1.99905644, 2.9062914 ]])

In [86]:
# 返回小数部分和整数部分
np.modf(arr)

(array([[0.98641629, 0.57231039, 0.24129427],
        [0.13161129, 0.2478735 , 0.89127189],
        [0.3985282 , 0.99905644, 0.9062914 ]]), array([[0., 1., 0.],
        [2., 0., 0.],
        [0., 1., 2.]]))

In [87]:
a,b = np.modf(arr)

In [88]:
print(a)
print(b)

[[0.98641629 0.57231039 0.24129427]
 [0.13161129 0.2478735  0.89127189]
 [0.3985282  0.99905644 0.9062914 ]]
[[0. 1. 0.]
 [2. 0. 0.]
 [0. 1. 2.]]


常用的二元通用函数

In [89]:
#返回两个数组求和的结果
np.add(arr1,arr2)

array([[0.43242737, 2.38173394, 4.57802072],
       [0.82846985, 2.91816669, 4.10845464],
       [0.99507329, 2.53545276, 4.45662288]])

In [90]:
# 求每个元素的平方
np.power(arr,2)

array([[0.97301709, 2.47215997, 0.05822292],
       [4.54376668, 0.06144127, 0.79436558],
       [0.15882472, 3.99622666, 8.44652972]])

In [91]:
# 返回两个数组每个位置较大的元素
np.maximum(arr1,arr2)

array([[0.43242737, 2.        , 4.        ],
       [0.82846985, 2.        , 4.        ],
       [0.99507329, 2.        , 4.        ]])

In [92]:
# 使用meshgrid()方法生成坐标矩阵
arr = np.arange(-5,5)
arr

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [93]:
xs,ys = np.meshgrid(arr,arr)

In [94]:
xs

array([[-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4]])

In [95]:
ys

array([[-5, -5, -5, -5, -5, -5, -5, -5, -5, -5],
       [-4, -4, -4, -4, -4, -4, -4, -4, -4, -4],
       [-3, -3, -3, -3, -3, -3, -3, -3, -3, -3],
       [-2, -2, -2, -2, -2, -2, -2, -2, -2, -2],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3],
       [ 4,  4,  4,  4,  4,  4,  4,  4,  4,  4]])

np.where(判断条件，真时的值，假时的值)

In [96]:
arr

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [97]:
arr = arr.reshape(2,5)

In [98]:
arr

array([[-5, -4, -3, -2, -1],
       [ 0,  1,  2,  3,  4]])

In [99]:
np.where(arr>0,1,-1)

array([[-1, -1, -1, -1, -1],
       [-1,  1,  1,  1,  1]])

In [100]:
arr2 = np.random.rand(2,5)
arr2

array([[0.31377976, 0.31695801, 0.63785132, 0.31470252, 0.25290025],
       [0.12033238, 0.92904214, 0.73598478, 0.21590452, 0.22630536]])

In [101]:
np.where(arr>0,1,arr2)

array([[0.31377976, 0.31695801, 0.63785132, 0.31470252, 0.25290025],
       [0.12033238, 1.        , 1.        , 1.        , 1.        ]])

描述性统计方法

In [102]:
arr1

array([[0, 2, 4]])

In [103]:
arr1.sum()

6

In [104]:
np.sum(arr1)

6

In [105]:
np.mean(arr1)

2.0

In [106]:
arr1.mean()

2.0

In [107]:
np.std(arr1)

1.632993161855452

In [108]:
arr1.std()

1.632993161855452

In [109]:
np.var(arr1)

2.6666666666666665

In [110]:
arr1.var()

2.6666666666666665

In [111]:
# 计算累计和
np.cumsum(arr1)

array([0, 2, 6], dtype=int32)

In [112]:
arr1.cumsum()

array([0, 2, 6], dtype=int32)

In [113]:
# 计算累计积
np.cumprod(arr1)

array([0, 0, 0], dtype=int32)

In [114]:
arr1.cumprod()

array([0, 0, 0], dtype=int32)

In [115]:
print(np.min(arr1))
print(arr1.min())

0
0


In [116]:
print(np.max(arr1))
print(arr1.max())

4
4


In [117]:
# 最小值的位置
print(np.argmin(arr1))
print(arr1.argmin())

0
0


In [118]:
# 最大值的位置
print(np.argmax(arr1))
print(arr1.argmax())

2
2


布尔数组的sum()，any()，all()方法

In [119]:
arr = np.random.randn(4,4)
arr

array([[-0.53292986,  2.87186677,  0.01298456,  1.25534123],
       [-0.38520125, -0.67992251, -1.0705042 , -1.17115856],
       [ 1.04367212, -0.78565217, -0.35611861, -0.5323811 ],
       [ 0.45886729,  1.32698915,  0.42337633, -0.48285849]])

In [120]:
arr = arr > 0
arr

array([[False,  True,  True,  True],
       [False, False, False, False],
       [ True, False, False, False],
       [ True,  True,  True, False]])

In [121]:
# 有多少个True
arr.sum()

7

In [122]:
# 是否有一个为True
arr.any()

True

In [123]:
# 是否全为True
arr.all()

False

对数组进行排序，默认进行升序排列

In [124]:
arr = np.random.randint(1,100,(3,4))
arr

array([[ 8, 68, 41, 79],
       [77, 99, 98, 11],
       [78, 13, 27,  2]])

In [125]:
# 对数组进行排序。将每一行的数组按照升序进行排序。
# 无返回值，直接作用于原数组
# 默认axis=1，按行进行操作
arr.sort()

In [126]:
arr

array([[ 8, 41, 68, 79],
       [11, 77, 98, 99],
       [ 2, 13, 27, 78]])

In [127]:
# axis=0对列的值进行排序，无返回值，直接作用于数组
arr.sort(axis=0)
arr

array([[ 2, 13, 27, 78],
       [ 8, 41, 68, 79],
       [11, 77, 98, 99]])

使用arr[::-1]将每行的顺序调转，每列的数值不变。先使用arr.sort(axis=0)，再使用arr[::-1]可实现对列中的每个值进行降序排列  
使用arr[:,::-1]将每列的顺序调转，每行的数值不变。先使用arr.sort(axis=1)，再使用arr[:,::-1]可实现对行中的每个值进行降序排列。

In [128]:
arr = np.random.randint(1,100,(4,4))
arr

array([[44, 17, 75, 83],
       [83, 67, 71, 35],
       [47, 46, 15, 66],
       [22, 27, 81, 54]])

In [129]:
arr.sort()
arr

array([[17, 44, 75, 83],
       [35, 67, 71, 83],
       [15, 46, 47, 66],
       [22, 27, 54, 81]])

In [130]:
arr[:,::-1]

array([[83, 75, 44, 17],
       [83, 71, 67, 35],
       [66, 47, 46, 15],
       [81, 54, 27, 22]])

In [131]:
arr

array([[17, 44, 75, 83],
       [35, 67, 71, 83],
       [15, 46, 47, 66],
       [22, 27, 54, 81]])

In [132]:
arr.sort(axis=0)
arr

array([[15, 27, 47, 66],
       [17, 44, 54, 81],
       [22, 46, 71, 83],
       [35, 67, 75, 83]])

In [133]:
arr[::-1]

array([[35, 67, 75, 83],
       [22, 46, 71, 83],
       [17, 44, 54, 81],
       [15, 27, 47, 66]])

使用np.unique(arr)获取唯一值，不论arr什么shape，返回值都是一维。  
arr没有unique()方法

In [134]:
arr = np.random.randint(1,10,15).reshape(3,5)
arr

array([[4, 1, 3, 8, 7],
       [2, 9, 6, 1, 7],
       [9, 3, 8, 6, 6]])

In [135]:
np.unique(arr)

array([1, 2, 3, 4, 6, 7, 8, 9])

如何通过数组取分位数  
1. 先将数组升序排序；
2. 再用数组的个数乘以分位数，取整得到n；
3. 使用索引的方式获取分位数

In [136]:
arr = np.random.randint(1,100,10)
arr

array([60, 30, 64, 29, 18,  8, 75, 74, 22, 95])

In [137]:
arr.sort()

In [138]:
arr

array([ 8, 18, 22, 29, 30, 60, 64, 74, 75, 95])

In [139]:
n = int(len(arr)*0.5)
arr[n]

60

In [140]:
arr[n-1]

30

np.in1d()用来判断数组的值是否在一个列表或者数组中，返回1维布尔数组

In [141]:
arr = np.random.randint(1,20,9).reshape(3,3)
arr

array([[16, 11,  5],
       [16, 18,  8],
       [16,  2, 19]])

In [142]:
arr_1 = np.unique(np.random.randint(1,20,9))
arr_1

array([ 1,  2,  3, 10, 11, 15, 16, 18])

In [143]:
np.in1d(arr,arr_1)

array([ True,  True, False,  True,  True, False,  True,  True, False])

In [144]:
arr_2 = np.random.randint(1,10,9).reshape(3,3)
arr_2

array([[6, 7, 4],
       [8, 2, 3],
       [8, 9, 6]])

In [145]:
arr

array([[16, 11,  5],
       [16, 18,  8],
       [16,  2, 19]])

In [146]:
# arr_2并不一定需要是一维数组才行
np.in1d(arr,arr_2)

array([False, False, False, False, False,  True, False,  True, False])

isin判断第一个数组的值是否在第2个数组或者列表中，返回一个布尔型数组，shape同第一个数组的shape。  
官方推荐使用isin而不是in1d。

In [147]:
np.isin(arr,arr_2)

array([[False, False, False],
       [False, False,  True],
       [False,  True, False]])

In [148]:
arr[np.isin(arr,arr_2)]

array([8, 2])

np.save()和np.load()存储和加载数组

In [149]:
np.save('test_arr',arr)

In [150]:
np.load('test_arr.npy')

array([[16, 11,  5],
       [16, 18,  8],
       [16,  2, 19]])