In [1]:
import numpy as np

使用np.arange()生成整数递增序列

In [2]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# 包含1，不包含10，步长为2
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

%time 计算代码执行时间，代码只执行一次，并且需要放在一行

In [4]:
arr = np.arange(10000)
%time for i in range(10000): arr**2

Wall time: 100 ms


%timeit 计算代码执行的时间，代码会重复执行多次并计算平均值，并且需要放在一行

In [5]:
# for循环冒号后面不换行也是可以的
%timeit for i in range(10000): arr*2

96.8 ms ± 4.3 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


datetime.datatime.now()获取程序开始和结束的时间

In [6]:
import datetime
start = datetime.datetime.now()
arr = np.arange(10000)
for i in range(10000):
    arr**2
end = datetime.datetime.now()
print('start time:{}'.format(start))
print('end time:{}'.format(end))
print(end - start)

start time:2019-12-23 22:50:05.445412
end time:2019-12-23 22:50:05.537239
0:00:00.091827


time.time()获取程序开始和结束的时间

In [7]:
import time
import datetime
start = time.time()
arr = np.arange(10000)
for i in range(10000):
    arr**2
end = time.time()
print('start time:{}'.format(start))
print('end time:{}'.format(end))
print(end - start)

start time:1577112605.5500145
end time:1577112605.637256
0.08724141120910645


timeit.timeit('',number=10000)计算''之间代码执行的时间

In [8]:
import timeit
timeit.timeit('arr = [1,2,3,4]',number=10000)

0.0013501999999974146

生成ndarray对象的方式有哪些？  
np.array()  
np.zeros()  
np.ones()  
np.arange()  
np.random.randint()  
np.random.randn()  
np.random.rand()  
np.random.random()  

In [9]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.ones(3)

array([1., 1., 1.])

In [13]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
# 第一个参数表示开始值，第二个参数表示结束值（不包含），第三个参数表示矩阵的shape
np.random.randint(2,5,3)

array([2, 4, 4])

In [15]:
np.random.randint(1,10,(2,3))

array([[1, 9, 8],
       [9, 5, 2]])

In [16]:
# 标准正态分布随机数
np.random.randn(2,3)

array([[ 1.07892168,  0.62105819, -1.91413429],
       [ 1.15163522,  1.45639462,  0.31038238]])

In [17]:
# 0-1之间随机分布数
np.random.rand(2,3)

array([[0.54153375, 0.81240922, 0.63875723],
       [0.17827441, 0.41704668, 0.24504877]])

In [18]:
# # 0-1之间随机分布数
np.random.random((2,3))

array([[0.30142679, 0.68169794, 0.61078725],
       [0.55020891, 0.56847322, 0.85630943]])

reshape方法用于转换矩阵的形状

In [19]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [20]:
# 生成二维数组，列为1
arr = np.arange(9).reshape(-1,1)
print(arr.shape)
print(arr)

(9, 1)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [21]:
# 生成二维数组，行为1
arr = np.arange(9).reshape(1,-1)
print(arr.shape)
print(arr)

(1, 9)
[[0 1 2 3 4 5 6 7 8]]


ndarray对象之间进行加减乘除的规则

In [22]:
arr1 = np.random.randint(1,20,9).reshape(3,3)
arr1

array([[15, 15,  8],
       [12, 12, 13],
       [ 6, 13, 15]])

In [23]:
arr1 + 1

array([[16, 16,  9],
       [13, 13, 14],
       [ 7, 14, 16]])

In [24]:
arr1 * 2

array([[30, 30, 16],
       [24, 24, 26],
       [12, 26, 30]])

In [25]:
arr2 = np.random.rand(9).reshape(3,3)
arr2

array([[0.06694945, 0.89258949, 0.43395615],
       [0.45904926, 0.19804178, 0.72671137],
       [0.56655054, 0.65578628, 0.80261283]])

In [26]:
arr1 + arr2

array([[15.06694945, 15.89258949,  8.43395615],
       [12.45904926, 12.19804178, 13.72671137],
       [ 6.56655054, 13.65578628, 15.80261283]])

In [27]:
arr1 - arr2

array([[14.93305055, 14.10741051,  7.56604385],
       [11.54095074, 11.80195822, 12.27328863],
       [ 5.43344946, 12.34421372, 14.19738717]])

In [28]:
arr1 * arr2

array([[ 1.00424172, 13.38884237,  3.47164917],
       [ 5.50859114,  2.37650134,  9.44724779],
       [ 3.39930326,  8.5252216 , 12.03919244]])

In [29]:
# 点乘，arr1的列数等于arr2的行数
arr1.dot(arr2)

array([[12.422385  , 21.60575926, 23.83091535],
       [13.67714158, 21.61279684, 24.36197696],
       [14.86759524, 17.76687422, 24.09017711]])

In [30]:
arr1 / arr2

array([[224.04964318,  16.80503764,  18.43504251],
       [ 26.14098529,  60.59327536,  17.88880781],
       [ 10.59040552,  19.82353162,  18.68896116]])

两个数组进行比较会生成布尔数组

In [31]:
arr1 = np.random.rand(9).reshape(3,3)
arr1

array([[0.99297829, 0.14425181, 0.91531629],
       [0.34813295, 0.66511863, 0.03166458],
       [0.36135383, 0.46057161, 0.6160467 ]])

In [32]:
arr2 = np.random.rand(9).reshape(3,3)
arr2

array([[0.9923249 , 0.73403242, 0.63601142],
       [0.35066581, 0.23424808, 0.31931471],
       [0.25890462, 0.94766329, 0.13383608]])

In [33]:
arr1 > arr2

array([[ True, False,  True],
       [False,  True, False],
       [ True, False,  True]])

shape属性表示数组的形状
ndim属性表示数组的维度

In [34]:
print(arr1.shape)
print(arr1.ndim)

(3, 3)
2


In [35]:
arr1 = np.arange(3)
print(arr1.shape)
print(arr1.ndim)

(3,)
1


In [36]:
arr1 = np.array([[1,2,3]])
print(arr1.shape)
print(arr1.ndim)

(1, 3)
2


In [37]:
arr1 = np.array([[1],[2],[3]])
print(arr1.shape)
print(arr1.ndim)

(3, 1)
2


dtype属性表示数组的数据类型

In [38]:
arr = np.arange(9).reshape(3,3)
arr.dtype

dtype('int32')

In [39]:
arr = np.random.rand(3,3)
arr.dtype

dtype('float64')

In [40]:
arr = np.array([['helloo','world'],['this','is']])
arr.dtype

dtype('<U6')

In [41]:
arr = np.array([True,False,True,True])
arr.dtype

dtype('bool')

使用astype方法进行数据类型转换

In [42]:
arr = np.array([True,False,True,True]).astype(int)
print(arr)
print(arr.dtype)

[1 0 1 1]
int32


In [43]:
arr = arr.astype(float)
print(arr)
print(arr.dtype)

[1. 0. 1. 1.]
float64


计算次方和开方

In [44]:
arr = np.arange(4)
print(arr**2)
print(np.power(arr,2))
print(np.square(arr))

[0 1 4 9]
[0 1 4 9]
[0 1 4 9]


In [45]:
print(arr**0.5)
print(np.power(arr,0.5))
print(np.sqrt(arr))

[0.         1.         1.41421356 1.73205081]
[0.         1.         1.41421356 1.73205081]
[0.         1.         1.41421356 1.73205081]


数组的索引

In [46]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [47]:
arr[2]

array([6, 7, 8])

In [48]:
arr[2][1]

7

In [49]:
arr[2,1]

7

数组的切片，包含冒号左边的数字，不包含右边的数字。

In [58]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [59]:
arr[0:1]

array([[0, 1, 2]])

In [60]:
arr[1:3]

array([[3, 4, 5],
       [6, 7, 8]])

In [61]:
arr[0:2,1:3]

array([[1, 2],
       [4, 5]])

对切片的修改，会反映到原始数组上

In [62]:
arr[0:1,2] = 4
arr

array([[0, 1, 4],
       [3, 4, 5],
       [6, 7, 8]])

使用copy()方法进行复制，再进行修改，则不影响原始数组

In [63]:
arr1 = arr[0:1].copy()
arr1

array([[0, 1, 4]])

In [64]:
arr1[0,1] = 2
arr1

array([[0, 2, 4]])

In [65]:
arr

array([[0, 1, 4],
       [3, 4, 5],
       [6, 7, 8]])

什么是切片索引？将切片与索引同时使用，可以得到低纬度的数组。

In [66]:
arr[0:2,2]

array([4, 5])

如何使用布尔索引？

In [69]:
arr = np.random.randint(1,100,(4,3))
arr

array([[25, 23, 96],
       [73, 29, 87],
       [23, 42, 28],
       [43, 90, 22]])

In [70]:
arr[:,2] > 30

array([ True,  True, False, False])

In [71]:
arr[arr[:,2] > 30]

array([[25, 23, 96],
       [73, 29, 87]])

In [72]:
arr[2,:] > 30

array([False,  True, False])

In [73]:
arr[:,arr[2,:] > 30]

array([[23],
       [29],
       [42],
       [90]])

如何使用神奇索引？

In [76]:
arr

array([[25, 23, 96],
       [73, 29, 87],
       [23, 42, 28],
       [43, 90, 22]])

In [75]:
arr[[2,1,0,3]]

array([[23, 42, 28],
       [73, 29, 87],
       [25, 23, 96],
       [43, 90, 22]])

In [78]:
arr[:,[2,1,0]]

array([[96, 23, 25],
       [87, 29, 73],
       [28, 42, 23],
       [22, 90, 43]])