In [1]:
import numpy as np

使用np.arange()生成整数递增序列

In [2]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# 包含1，不包含10，步长为2
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

%time 计算代码执行时间，代码只执行一次，并且需要放在一行

In [11]:
arr = np.arange(10000)
%time for i in range(10000): arr**2

Wall time: 99.9 ms


%timeit 计算代码执行的时间，代码会重复执行多次并计算平均值，并且需要放在一行

In [13]:
# for循环冒号后面不换行也是可以的
%timeit for i in range(10000): arr*2

93.1 ms ± 610 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


datetime.datatime.now()获取程序开始和结束的时间

In [16]:
import datetime
start = datetime.datetime.now()
arr = np.arange(10000)
for i in range(10000):
    arr**2
end = datetime.datetime.now()
print('start time:{}'.format(start))
print('end time:{}'.format(end))
print(end - start)

start time:2019-12-22 21:57:02.911599
end time:2019-12-22 21:57:03.016557
0:00:00.104958


time.time()获取程序开始和结束的时间

In [18]:
import time
import datetime
start = time.time()
arr = np.arange(10000)
for i in range(10000):
    arr**2
end = time.time()
print('start time:{}'.format(start))
print('end time:{}'.format(end))
print(end - start)

start time:1577023222.813327
end time:1577023222.9192648
0.10593771934509277


timeit.timeit('',number=10000)计算''之间代码执行的时间

In [28]:
import timeit
timeit.timeit('arr = [1,2,3,4]',number=10000)

0.0022818999998435174

生成ndarray对象的方式有哪些？  
np.array()  
np.zeros()  
np.ones()  
np.arange()  
np.random.randint()  
np.random.randn()  
np.random.rand()  
np.random.random()  

In [29]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [30]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [31]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
np.ones(3)

array([1., 1., 1.])

In [34]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [35]:
# 第一个参数表示开始值，第二个参数表示结束值（不包含），第三个参数表示矩阵的shape
np.random.randint(2,5,3)

array([4, 4, 3])

In [36]:
np.random.randint(1,10,(2,3))

array([[6, 5, 4],
       [3, 6, 8]])

In [37]:
# 标准正态分布随机数
np.random.randn(2,3)

array([[ 0.58119302,  0.27169025, -0.80196342],
       [ 0.49850657,  0.32108529,  1.26775323]])

In [38]:
# 0-1之间随机分布数
np.random.rand(2,3)

array([[0.69559037, 0.63781873, 0.79090641],
       [0.89508907, 0.65353885, 0.62439395]])

In [40]:
# # 0-1之间随机分布数
np.random.random((2,3))

array([[0.69144027, 0.59535835, 0.36510722],
       [0.16146658, 0.81270028, 0.16686601]])

reshape方法用于转换矩阵的形状

In [41]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [49]:
# 生成二维数组，列为1
arr = np.arange(9).reshape(-1,1)
print(arr.shape)
print(arr)

(9, 1)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [50]:
# 生成二维数组，行为1
arr = np.arange(9).reshape(1,-1)
print(arr.shape)
print(arr)

(1, 9)
[[0 1 2 3 4 5 6 7 8]]


ndarray对象之间进行加减乘除的规则

In [52]:
arr1 = np.random.randint(1,20,9).reshape(3,3)
arr1

array([[ 8,  6,  4],
       [13, 17, 12],
       [ 7,  8,  8]])

In [53]:
arr1 + 1

array([[ 9,  7,  5],
       [14, 18, 13],
       [ 8,  9,  9]])

In [54]:
arr1 * 2

array([[16, 12,  8],
       [26, 34, 24],
       [14, 16, 16]])

In [57]:
arr2 = np.random.rand(9).reshape(3,3)
arr2

array([[0.05025794, 0.22471427, 0.47783522],
       [0.81884322, 0.65569679, 0.01472996],
       [0.73878961, 0.79891215, 0.35171122]])

In [58]:
arr1 + arr2

array([[ 8.05025794,  6.22471427,  4.47783522],
       [13.81884322, 17.65569679, 12.01472996],
       [ 7.73878961,  8.79891215,  8.35171122]])

In [59]:
arr1 - arr2

array([[ 7.94974206,  5.77528573,  3.52216478],
       [12.18115678, 16.34430321, 11.98527004],
       [ 6.26121039,  7.20108785,  7.64828878]])

In [60]:
arr1 * arr2

array([[ 0.40206353,  1.34828565,  1.91134089],
       [10.64496186, 11.14684537,  0.17675947],
       [ 5.1715273 ,  6.39129718,  2.81368979]])

In [62]:
# 点乘，arr1的列数等于arr2的行数
arr1.dot(arr2)

array([[ 8.2702813 ,  8.92754351,  5.31790641],
       [23.43916333, 23.65507672, 10.68280183],
       [12.81286825, 13.2098714 ,  6.27637599]])

In [61]:
arr1 / arr2

array([[159.17882588,  26.70057344,   8.37108654],
       [ 15.876055  ,  25.92661783, 814.66640852],
       [  9.47495724,  10.01361667,  22.74593317]])

两个数组进行比较会生成布尔数组

In [64]:
arr1 = np.random.rand(9).reshape(3,3)
arr1

array([[0.42016855, 0.09681922, 0.71753289],
       [0.65103914, 0.5517434 , 0.05207174],
       [0.05937361, 0.16107582, 0.95165984]])

In [65]:
arr2 = np.random.rand(9).reshape(3,3)
arr2

array([[0.74081258, 0.16807335, 0.55226705],
       [0.09807308, 0.6546247 , 0.80987704],
       [0.65927891, 0.92816875, 0.14050018]])

In [67]:
arr1 > arr2

array([[False, False,  True],
       [ True, False, False],
       [False, False,  True]])

shape属性表示数组的形状
ndim属性表示数组的维度

In [73]:
print(arr1.shape)
print(arr1.ndim)

(3, 1)
2


In [74]:
arr1 = np.arange(3)
print(arr1.shape)
print(arr1.ndim)

(3,)
1


In [75]:
arr1 = np.array([[1,2,3]])
print(arr1.shape)
print(arr1.ndim)

(1, 3)
2


In [76]:
arr1 = np.array([[1],[2],[3]])
print(arr1.shape)
print(arr1.ndim)

(3, 1)
2


dtype属性表示数组的数据类型

In [78]:
arr = np.arange(9).reshape(3,3)
arr.dtype

dtype('int32')

In [79]:
arr = np.random.rand(3,3)
arr.dtype

dtype('float64')

In [81]:
arr = np.array([['helloo','world'],['this','is']])
arr.dtype

dtype('<U6')

In [82]:
arr = np.array([True,False,True,True])
arr.dtype

dtype('bool')

使用astype方法进行数据类型转换

In [89]:
arr = np.array([True,False,True,True]).astype(int)
print(arr)
print(arr.dtype)

[1 0 1 1]
int32


In [90]:
arr = arr.astype(float)
print(arr)
print(arr.dtype)

[1. 0. 1. 1.]
float64


计算次方和开方

In [91]:
arr = np.arange(4)
print(arr**2)
print(np.power(arr,2))
print(np.square(arr))

[0 1 4 9]
[0 1 4 9]
[0 1 4 9]


In [92]:
print(arr**0.5)
print(np.power(arr,0.5))
print(np.sqrt(arr))

[0.         1.         1.41421356 1.73205081]
[0.         1.         1.41421356 1.73205081]
[0.         1.         1.41421356 1.73205081]


数组的索引

In [93]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [94]:
arr[2]

array([6, 7, 8])

In [95]:
arr[2][1]

7

In [96]:
arr[2,1]

7

数组的切片，包含冒号左边的数字，不包含右边的数字。

In [97]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [98]:
arr[0:1]

array([[0, 1, 2]])

In [99]:
arr[1:3]

array([[3, 4, 5],
       [6, 7, 8]])

In [100]:
arr[0:2,1:3]

array([[1, 2],
       [4, 5]])

对切片的修改，会反映到原始数组上

In [102]:
arr[0:1,2] = 4
arr

array([[0, 1, 4],
       [3, 4, 5],
       [6, 7, 8]])