In [1]:
import numpy as np

使用np.arange()生成整数递增序列

In [2]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# 包含1，不包含10，步长为2
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [4]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [5]:
np.linspace(1,10,10,endpoint=False)

array([1. , 1.9, 2.8, 3.7, 4.6, 5.5, 6.4, 7.3, 8.2, 9.1])

%time 计算代码执行时间，代码只执行一次，并且需要放在一行

In [6]:
arr = np.arange(10000)
%time for i in range(10000): arr**2

Wall time: 112 ms


%timeit 计算代码执行的时间，代码会重复执行多次并计算平均值，并且需要放在一行

In [7]:
# for循环冒号后面不换行也是可以的
%timeit for i in range(10000): arr*2

90.2 ms ± 794 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


datetime.datatime.now()获取程序开始和结束的时间

In [8]:
import datetime
start = datetime.datetime.now()
arr = np.arange(10000)
for i in range(10000):
    arr**2
end = datetime.datetime.now()
print('start time:{}'.format(start))
print('end time:{}'.format(end))
print(end - start)

start time:2020-01-04 12:07:42.847822
end time:2020-01-04 12:07:42.957761
0:00:00.109939


time.time()获取程序开始和结束的时间

In [9]:
import time
import datetime
start = time.time()
arr = np.arange(10000)
for i in range(10000):
    arr**2
end = time.time()
print('start time:{}'.format(start))
print('end time:{}'.format(end))
print(end - start)

start time:1578110862.967735
end time:1578110863.0676777
0.09994268417358398


timeit.timeit('',number=10000)计算''之间代码执行的时间

In [10]:
import timeit
timeit.timeit('arr = [1,2,3,4]',number=10000)

0.0006747000000011383

生成ndarray对象的方式有哪些？  
np.array()  
np.zeros()  
np.ones()  
np.arange()  
np.random.randint()  
np.random.randn()  
np.random.rand()  
np.random.random()  
np.linspace()

In [11]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [12]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [13]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [14]:
np.ones(3)

array([1., 1., 1.])

In [15]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [16]:
# 第一个参数表示开始值，第二个参数表示结束值（不包含），第三个参数表示矩阵的shape
np.random.randint(2,5,3)

array([3, 4, 3])

In [17]:
np.random.randint(1,10,(2,3))

array([[5, 3, 1],
       [7, 1, 6]])

In [18]:
# 标准正态分布随机数
np.random.randn(2,3)

array([[ 0.43353948, -0.3107256 ,  0.42197677],
       [-0.88545988,  0.48925704,  2.16812076]])

In [19]:
# 0-1之间随机分布数
np.random.rand(2,3)

array([[0.08202511, 0.01240057, 0.41182461],
       [0.29493977, 0.64969788, 0.72469362]])

In [20]:
# # 0-1之间随机分布数
np.random.random((2,3))

array([[4.10844770e-01, 2.61773777e-01, 5.07489478e-01],
       [5.81866735e-01, 8.46269800e-01, 3.45141376e-05]])

reshape方法用于转换矩阵的形状

In [21]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [22]:
# 生成二维数组，列为1
arr = np.arange(9).reshape(-1,1)
print(arr.shape)
print(arr)

(9, 1)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [23]:
# 生成二维数组，行为1
arr = np.arange(9).reshape(1,-1)
print(arr.shape)
print(arr)

(1, 9)
[[0 1 2 3 4 5 6 7 8]]


reshape(-1,n)将原数组转换成列为n的数组，行自行计算。数组元素的个数需要能够被n整除。

In [24]:
arr = np.arange(12).reshape(-1,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

reshape(n,-1)将原数组转换成行为n的数组，列自行计算。数组元素的个数需要能够被n整除。

In [25]:
arr = np.arange(12).reshape(3,-1)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

ndarray对象之间进行加减乘除的规则

In [26]:
arr1 = np.random.randint(1,20,9).reshape(3,3)
arr1

array([[ 9, 17, 13],
       [12,  2, 16],
       [ 5, 10,  9]])

In [27]:
arr1 + 1

array([[10, 18, 14],
       [13,  3, 17],
       [ 6, 11, 10]])

In [28]:
arr1 * 2

array([[18, 34, 26],
       [24,  4, 32],
       [10, 20, 18]])

In [29]:
arr2 = np.random.rand(9).reshape(3,3)
arr2

array([[0.05699585, 0.54653518, 0.2394251 ],
       [0.31901053, 0.81470154, 0.61599665],
       [0.36387867, 0.77470947, 0.69023875]])

In [30]:
arr1 + arr2

array([[ 9.05699585, 17.54653518, 13.2394251 ],
       [12.31901053,  2.81470154, 16.61599665],
       [ 5.36387867, 10.77470947,  9.69023875]])

In [31]:
arr1 - arr2

array([[ 8.94300415, 16.45346482, 12.7605749 ],
       [11.68098947,  1.18529846, 15.38400335],
       [ 4.63612133,  9.22529053,  8.30976125]])

两个数组相同位置的元素进行相乘

In [32]:
arr1 = np.random.rand(3,3)
arr2 = np.random.rand(3,3)

In [33]:
arr1

array([[0.73161749, 0.62359341, 0.04026331],
       [0.09474114, 0.53773518, 0.42204198],
       [0.72073773, 0.23533936, 0.61081575]])

In [34]:
arr2

array([[0.25695337, 0.60677395, 0.34380781],
       [0.28699878, 0.84513031, 0.55502579],
       [0.47527818, 0.80763117, 0.28418669]])

In [35]:
arr1 * arr2

array([[0.18799158, 0.37838024, 0.01384284],
       [0.02719059, 0.4544563 , 0.23424418],
       [0.34255092, 0.19006741, 0.1735857 ]])

计算两个矩阵的点积（内积）

In [36]:
# 点乘，arr1的列数等于arr2的行数
arr1.dot(arr2)

array([[0.38609841, 1.00346204, 0.60908853],
       [0.37926074, 0.85279701, 0.45096835],
       [0.5430455 , 1.12953115, 0.55200038]])

In [37]:
np.dot(arr1,arr2)

array([[0.38609841, 1.00346204, 0.60908853],
       [0.37926074, 0.85279701, 0.45096835],
       [0.5430455 , 1.12953115, 0.55200038]])

In [38]:
arr1 / arr2

array([[2.84727723, 1.02771949, 0.11710994],
       [0.3301099 , 0.63627487, 0.76040066],
       [1.5164545 , 0.2913946 , 2.14934683]])

两个数组进行比较会生成布尔数组

In [39]:
arr1 = np.random.rand(9).reshape(3,3)
arr1

array([[0.34673383, 0.47479566, 0.09907449],
       [0.92547562, 0.08162022, 0.96195465],
       [0.12516943, 0.0904783 , 0.59254081]])

In [40]:
arr2 = np.random.rand(9).reshape(3,3)
arr2

array([[0.72153959, 0.25578076, 0.13802248],
       [0.50136634, 0.26241488, 0.65773046],
       [0.48889214, 0.08306299, 0.90196996]])

In [41]:
arr1 > arr2

array([[False,  True, False],
       [ True, False,  True],
       [False,  True, False]])

shape属性表示数组的形状
ndim属性表示数组的维度

In [42]:
print(arr1.shape)
print(arr1.ndim)

(3, 3)
2


In [43]:
arr1 = np.arange(3)
print(arr1.shape)
print(arr1.ndim)

(3,)
1


In [44]:
arr1 = np.array([[1,2,3]])
print(arr1.shape)
print(arr1.ndim)

(1, 3)
2


In [45]:
arr1 = np.array([[1],[2],[3]])
print(arr1.shape)
print(arr1.ndim)

(3, 1)
2


dtype属性表示数组的数据类型

In [46]:
arr = np.arange(9).reshape(3,3)
arr.dtype

dtype('int32')

In [47]:
arr = np.random.rand(3,3)
arr.dtype

dtype('float64')

In [48]:
arr = np.array([['helloo','world'],['this','is']])
arr.dtype

dtype('<U6')

In [49]:
arr = np.array([True,False,True,True])
arr.dtype

dtype('bool')

使用astype方法进行数据类型转换

In [50]:
arr = np.array([True,False,True,True]).astype(int)
print(arr)
print(arr.dtype)

[1 0 1 1]
int32


In [51]:
arr = arr.astype(float)
print(arr)
print(arr.dtype)

[1. 0. 1. 1.]
float64


计算次方和开方

In [52]:
arr = np.arange(4)
print(arr**2)
print(np.power(arr,2))
print(np.square(arr))

[0 1 4 9]
[0 1 4 9]
[0 1 4 9]


In [53]:
print(arr**0.5)
print(np.power(arr,0.5))
print(np.sqrt(arr))

[0.         1.         1.41421356 1.73205081]
[0.         1.         1.41421356 1.73205081]
[0.         1.         1.41421356 1.73205081]


数组的索引

In [54]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [55]:
arr[2]

array([6, 7, 8])

In [56]:
arr[2][1]

7

In [57]:
arr[2,1]

7

数组的切片，包含冒号左边的数字，不包含右边的数字。

In [58]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [59]:
arr[0:1]

array([[0, 1, 2]])

In [60]:
arr[1:3]

array([[3, 4, 5],
       [6, 7, 8]])

In [61]:
arr[0:2,1:3]

array([[1, 2],
       [4, 5]])

对切片的修改，会反映到原始数组上

In [62]:
arr[0:1,2] = 4
arr

array([[0, 1, 4],
       [3, 4, 5],
       [6, 7, 8]])

使用copy()方法进行复制，再进行修改，则不影响原始数组

In [63]:
arr1 = arr[0:1].copy()
arr1

array([[0, 1, 4]])

In [64]:
arr1[0,1] = 2
arr1

array([[0, 2, 4]])

In [65]:
arr

array([[0, 1, 4],
       [3, 4, 5],
       [6, 7, 8]])

什么是切片索引？将切片与索引同时使用，可以得到低纬度的数组。

In [66]:
arr[0:2,2]

array([4, 5])

如何使用布尔索引？

In [67]:
arr = np.random.randint(1,100,(4,3))
arr

array([[ 6, 70,  2],
       [91, 54, 42],
       [35,  6, 27],
       [64, 28, 49]])

In [68]:
arr[:,2] > 30

array([False,  True, False,  True])

In [69]:
arr[arr[:,2] > 30]

array([[91, 54, 42],
       [64, 28, 49]])

In [70]:
arr[2,:] > 30

array([ True, False, False])

In [71]:
arr[:,arr[2,:] > 30]

array([[ 6],
       [91],
       [35],
       [64]])

如何使用神奇索引？  
所谓的神奇索引，就是使用整数列表来对原数组进行排序，或者选取想要的行数。

In [72]:
arr

array([[ 6, 70,  2],
       [91, 54, 42],
       [35,  6, 27],
       [64, 28, 49]])

In [73]:
arr[[2,1,0,3]]

array([[35,  6, 27],
       [91, 54, 42],
       [ 6, 70,  2],
       [64, 28, 49]])

In [74]:
arr[:,[2,1,0]]

array([[ 2, 70,  6],
       [42, 54, 91],
       [27,  6, 35],
       [49, 28, 64]])

In [75]:
arr

array([[ 6, 70,  2],
       [91, 54, 42],
       [35,  6, 27],
       [64, 28, 49]])

数组的转置

In [76]:
arr.T

array([[ 6, 91, 35, 64],
       [70, 54,  6, 28],
       [ 2, 42, 27, 49]])

常用的一元通用函数

In [77]:
arr

array([[ 6, 70,  2],
       [91, 54, 42],
       [35,  6, 27],
       [64, 28, 49]])

In [78]:
# 求平方根
np.sqrt(arr)

array([[2.44948974, 8.36660027, 1.41421356],
       [9.53939201, 7.34846923, 6.4807407 ],
       [5.91607978, 2.44948974, 5.19615242],
       [8.        , 5.29150262, 7.        ]])

In [79]:
# 求平方
np.square(arr)

array([[  36, 4900,    4],
       [8281, 2916, 1764],
       [1225,   36,  729],
       [4096,  784, 2401]], dtype=int32)

In [80]:
# 求e为底的结果
np.exp(arr)

array([[4.03428793e+02, 2.51543867e+30, 7.38905610e+00],
       [3.31740010e+39, 2.83075330e+23, 1.73927494e+18],
       [1.58601345e+15, 4.03428793e+02, 5.32048241e+11],
       [6.23514908e+27, 1.44625706e+12, 1.90734657e+21]])

In [81]:
arr = arr * -1
arr

array([[ -6, -70,  -2],
       [-91, -54, -42],
       [-35,  -6, -27],
       [-64, -28, -49]])

求绝对值

In [82]:
np.abs(arr)

array([[ 6, 70,  2],
       [91, 54, 42],
       [35,  6, 27],
       [64, 28, 49]])

In [83]:
np.fabs(arr)

array([[ 6., 70.,  2.],
       [91., 54., 42.],
       [35.,  6., 27.],
       [64., 28., 49.]])

In [84]:
# np.modf()返回小数部分和整数部分
arr = np.random.rand(3,3)
arr

array([[0.60015196, 0.99346898, 0.90151352],
       [0.54771672, 0.76995413, 0.81404886],
       [0.65945267, 0.84977307, 0.05385871]])

In [85]:
arr = arr * 3
arr

array([[1.80045588, 2.98040695, 2.70454057],
       [1.64315015, 2.3098624 , 2.44214659],
       [1.97835801, 2.54931921, 0.16157613]])

In [86]:
# 返回小数部分和整数部分
np.modf(arr)

(array([[0.80045588, 0.98040695, 0.70454057],
        [0.64315015, 0.3098624 , 0.44214659],
        [0.97835801, 0.54931921, 0.16157613]]), array([[1., 2., 2.],
        [1., 2., 2.],
        [1., 2., 0.]]))

In [87]:
a,b = np.modf(arr)

In [88]:
print(a)
print(b)

[[0.80045588 0.98040695 0.70454057]
 [0.64315015 0.3098624  0.44214659]
 [0.97835801 0.54931921 0.16157613]]
[[1. 2. 2.]
 [1. 2. 2.]
 [1. 2. 0.]]


常用的二元通用函数

In [89]:
#返回两个数组求和的结果
np.add(arr1,arr2)

array([[0.72153959, 2.25578076, 4.13802248],
       [0.50136634, 2.26241488, 4.65773046],
       [0.48889214, 2.08306299, 4.90196996]])

In [90]:
# 求每个元素的平方
np.power(arr,2)

array([[3.24164136, 8.88282557, 7.31453971],
       [2.69994241, 5.3354643 , 5.96407999],
       [3.91390042, 6.49902843, 0.02610684]])

In [91]:
# 返回两个数组每个位置较大的元素
np.maximum(arr1,arr2)

array([[0.72153959, 2.        , 4.        ],
       [0.50136634, 2.        , 4.        ],
       [0.48889214, 2.        , 4.        ]])

In [92]:
# 使用meshgrid()方法生成坐标矩阵
arr = np.arange(-5,5)
arr

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [93]:
xs,ys = np.meshgrid(arr,arr)

In [94]:
xs

array([[-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4]])

In [95]:
ys

array([[-5, -5, -5, -5, -5, -5, -5, -5, -5, -5],
       [-4, -4, -4, -4, -4, -4, -4, -4, -4, -4],
       [-3, -3, -3, -3, -3, -3, -3, -3, -3, -3],
       [-2, -2, -2, -2, -2, -2, -2, -2, -2, -2],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3],
       [ 4,  4,  4,  4,  4,  4,  4,  4,  4,  4]])

np.where(判断条件，真时的值，假时的值)

In [96]:
arr

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [97]:
arr = arr.reshape(2,5)

In [98]:
arr

array([[-5, -4, -3, -2, -1],
       [ 0,  1,  2,  3,  4]])

In [99]:
np.where(arr>0,1,-1)

array([[-1, -1, -1, -1, -1],
       [-1,  1,  1,  1,  1]])

In [100]:
arr2 = np.random.rand(2,5)
arr2

array([[0.21218406, 0.3058369 , 0.43765151, 0.15324949, 0.01347868],
       [0.6838436 , 0.44758744, 0.96093672, 0.82019459, 0.62534689]])

In [101]:
np.where(arr>0,1,arr2)

array([[0.21218406, 0.3058369 , 0.43765151, 0.15324949, 0.01347868],
       [0.6838436 , 1.        , 1.        , 1.        , 1.        ]])

描述性统计方法

In [102]:
arr1

array([[0, 2, 4]])

In [103]:
arr1.sum()

6

In [104]:
np.sum(arr1)

6

In [105]:
np.mean(arr1)

2.0

In [106]:
arr1.mean()

2.0

In [107]:
np.std(arr1)

1.632993161855452

In [108]:
arr1.std()

1.632993161855452

In [109]:
np.var(arr1)

2.6666666666666665

In [110]:
arr1.var()

2.6666666666666665

In [111]:
# 计算累计和
np.cumsum(arr1)

array([0, 2, 6], dtype=int32)

In [112]:
arr1.cumsum()

array([0, 2, 6], dtype=int32)

In [113]:
# 计算累计积
np.cumprod(arr1)

array([0, 0, 0], dtype=int32)

In [114]:
arr1.cumprod()

array([0, 0, 0], dtype=int32)

In [115]:
print(np.min(arr1))
print(arr1.min())

0
0


In [116]:
print(np.max(arr1))
print(arr1.max())

4
4


In [117]:
# 最小值的位置
print(np.argmin(arr1))
print(arr1.argmin())

0
0


In [118]:
# 最大值的位置
print(np.argmax(arr1))
print(arr1.argmax())

2
2


布尔数组的sum()，any()，all()方法

In [119]:
arr = np.random.randn(4,4)
arr

array([[-0.10025104,  0.00844232, -1.82507522, -1.09710309],
       [-0.23543281,  0.42748857, -1.10067102,  0.4567744 ],
       [ 0.03485745,  0.95349871,  0.4486529 , -0.2843464 ],
       [-1.02486825, -0.39945541, -1.25531002,  1.09581685]])

In [120]:
arr = arr > 0
arr

array([[False,  True, False, False],
       [False,  True, False,  True],
       [ True,  True,  True, False],
       [False, False, False,  True]])

In [121]:
# 有多少个True
arr.sum()

7

In [122]:
# 是否有一个为True
arr.any()

True

In [123]:
# 是否全为True
arr.all()

False

对数组进行排序，默认进行升序排列

In [124]:
arr = np.random.randint(1,100,(3,4))
arr

array([[ 9, 51, 65, 89],
       [34, 58, 30, 50],
       [52, 58, 63, 58]])

In [125]:
# 对数组进行排序。将每一行的数组按照升序进行排序。
# 无返回值，直接作用于原数组
# 默认axis=1，按行进行操作
arr.sort()

In [126]:
arr

array([[ 9, 51, 65, 89],
       [30, 34, 50, 58],
       [52, 58, 58, 63]])

In [127]:
# axis=0对列的值进行排序，无返回值，直接作用于数组
arr.sort(axis=0)
arr

array([[ 9, 34, 50, 58],
       [30, 51, 58, 63],
       [52, 58, 65, 89]])

使用arr[::-1]将每行的顺序调转，每列的数值不变。先使用arr.sort(axis=0)，再使用arr[::-1]可实现对列中的每个值进行降序排列  
使用arr[:,::-1]将每列的顺序调转，每行的数值不变。先使用arr.sort(axis=1)，再使用arr[:,::-1]可实现对行中的每个值进行降序排列。

In [128]:
arr = np.random.randint(1,100,(4,4))
arr

array([[69, 73, 10, 94],
       [26, 95, 58, 38],
       [22, 14, 48, 50],
       [78, 67, 13,  9]])

In [129]:
arr.sort()
arr

array([[10, 69, 73, 94],
       [26, 38, 58, 95],
       [14, 22, 48, 50],
       [ 9, 13, 67, 78]])

In [130]:
arr[:,::-1]

array([[94, 73, 69, 10],
       [95, 58, 38, 26],
       [50, 48, 22, 14],
       [78, 67, 13,  9]])

In [131]:
arr

array([[10, 69, 73, 94],
       [26, 38, 58, 95],
       [14, 22, 48, 50],
       [ 9, 13, 67, 78]])

In [132]:
arr.sort(axis=0)
arr

array([[ 9, 13, 48, 50],
       [10, 22, 58, 78],
       [14, 38, 67, 94],
       [26, 69, 73, 95]])

In [133]:
arr[::-1]

array([[26, 69, 73, 95],
       [14, 38, 67, 94],
       [10, 22, 58, 78],
       [ 9, 13, 48, 50]])

使用np.unique(arr)获取唯一值，不论arr什么shape，返回值都是一维。  
arr没有unique()方法

In [134]:
arr = np.random.randint(1,10,15).reshape(3,5)
arr

array([[2, 4, 2, 7, 4],
       [3, 7, 4, 9, 6],
       [8, 3, 3, 5, 3]])

In [135]:
np.unique(arr)

array([2, 3, 4, 5, 6, 7, 8, 9])

如何通过数组取分位数  
1. 先将数组升序排序；
2. 再用数组的个数乘以分位数，取整得到n；
3. 使用索引的方式获取分位数

In [136]:
arr = np.random.randint(1,100,10)
arr

array([58, 92, 39, 87, 20, 96, 70, 67, 51, 74])

In [137]:
arr.sort()

In [138]:
arr

array([20, 39, 51, 58, 67, 70, 74, 87, 92, 96])

In [139]:
n = int(len(arr)*0.5)
arr[n]

70

In [140]:
arr[n-1]

67

np.in1d()用来判断数组的值是否在一个列表中，返回1维布尔数组

In [141]:
arr = np.random.randint(1,20,9).reshape(3,3)
arr

array([[ 7,  4, 16],
       [ 7, 16, 15],
       [10,  7, 11]])

In [142]:
arr_1 = np.unique(np.random.randint(1,20,9))
arr_1

array([ 1, 10, 11, 13, 16, 17, 19])

In [143]:
np.in1d(arr,arr_1)

array([False, False,  True, False,  True, False,  True, False,  True])

In [144]:
arr_2 = np.random.randint(1,10,9).reshape(3,3)
arr_2

array([[5, 1, 7],
       [2, 2, 1],
       [1, 8, 1]])

In [145]:
arr

array([[ 7,  4, 16],
       [ 7, 16, 15],
       [10,  7, 11]])

In [146]:
# arr2需要是一维数组才行
np.in1d(arr,arr2)

array([False, False, False, False, False, False, False, False, False])

np.save()和np.load()存储和加载数组

In [147]:
np.save('test_arr',arr)

In [148]:
np.load('test_arr.npy')

array([[ 7,  4, 16],
       [ 7, 16, 15],
       [10,  7, 11]])