In [1]:
import numpy as np

使用np.arange()生成整数递增序列

In [2]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# 包含1，不包含10，步长为2
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

%time 计算代码执行时间，代码只执行一次，并且需要放在一行

In [4]:
arr = np.arange(10000)
%time for i in range(10000): arr**2

Wall time: 112 ms


%timeit 计算代码执行的时间，代码会重复执行多次并计算平均值，并且需要放在一行

In [5]:
# for循环冒号后面不换行也是可以的
%timeit for i in range(10000): arr*2

95.1 ms ± 2.11 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


datetime.datatime.now()获取程序开始和结束的时间

In [6]:
import datetime
start = datetime.datetime.now()
arr = np.arange(10000)
for i in range(10000):
    arr**2
end = datetime.datetime.now()
print('start time:{}'.format(start))
print('end time:{}'.format(end))
print(end - start)

start time:2019-12-22 23:31:04.951752
end time:2019-12-22 23:31:05.055710
0:00:00.103958


time.time()获取程序开始和结束的时间

In [7]:
import time
import datetime
start = time.time()
arr = np.arange(10000)
for i in range(10000):
    arr**2
end = time.time()
print('start time:{}'.format(start))
print('end time:{}'.format(end))
print(end - start)

start time:1577028665.0656872
end time:1577028665.167627
0.10193991661071777


timeit.timeit('',number=10000)计算''之间代码执行的时间

In [8]:
import timeit
timeit.timeit('arr = [1,2,3,4]',number=10000)

0.001700599999999497

生成ndarray对象的方式有哪些？  
np.array()  
np.zeros()  
np.ones()  
np.arange()  
np.random.randint()  
np.random.randn()  
np.random.rand()  
np.random.random()  

In [9]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
np.ones(3)

array([1., 1., 1.])

In [13]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
# 第一个参数表示开始值，第二个参数表示结束值（不包含），第三个参数表示矩阵的shape
np.random.randint(2,5,3)

array([2, 4, 4])

In [15]:
np.random.randint(1,10,(2,3))

array([[7, 1, 5],
       [1, 4, 6]])

In [16]:
# 标准正态分布随机数
np.random.randn(2,3)

array([[ 0.19600067, -0.46162194,  1.0327372 ],
       [ 0.48682239, -0.33360613, -0.06870361]])

In [17]:
# 0-1之间随机分布数
np.random.rand(2,3)

array([[0.78529648, 0.02698206, 0.22622476],
       [0.54230472, 0.80316526, 0.7638401 ]])

In [18]:
# # 0-1之间随机分布数
np.random.random((2,3))

array([[0.54404751, 0.9612234 , 0.3560232 ],
       [0.34784057, 0.39947489, 0.70564431]])

reshape方法用于转换矩阵的形状

In [19]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [20]:
# 生成二维数组，列为1
arr = np.arange(9).reshape(-1,1)
print(arr.shape)
print(arr)

(9, 1)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [21]:
# 生成二维数组，行为1
arr = np.arange(9).reshape(1,-1)
print(arr.shape)
print(arr)

(1, 9)
[[0 1 2 3 4 5 6 7 8]]


ndarray对象之间进行加减乘除的规则

In [22]:
arr1 = np.random.randint(1,20,9).reshape(3,3)
arr1

array([[18,  7, 17],
       [ 4,  1, 11],
       [ 7, 14, 10]])

In [23]:
arr1 + 1

array([[19,  8, 18],
       [ 5,  2, 12],
       [ 8, 15, 11]])

In [24]:
arr1 * 2

array([[36, 14, 34],
       [ 8,  2, 22],
       [14, 28, 20]])

In [25]:
arr2 = np.random.rand(9).reshape(3,3)
arr2

array([[0.73242386, 0.71818206, 0.35341249],
       [0.25666276, 0.34963986, 0.43328411],
       [0.71777943, 0.75721757, 0.45076624]])

In [26]:
arr1 + arr2

array([[18.73242386,  7.71818206, 17.35341249],
       [ 4.25666276,  1.34963986, 11.43328411],
       [ 7.71777943, 14.75721757, 10.45076624]])

In [27]:
arr1 - arr2

array([[17.26757614,  6.28181794, 16.64658751],
       [ 3.74333724,  0.65036014, 10.56671589],
       [ 6.28222057, 13.24278243,  9.54923376]])

In [28]:
arr1 * arr2

array([[13.18362947,  5.02727443,  6.00801231],
       [ 1.02665105,  0.34963986,  4.76612525],
       [ 5.02445601, 10.60104595,  4.50766242]])

In [29]:
# 点乘，arr1的列数等于arr2的行数
arr1.dot(arr2)

array([[27.18251912, 28.2474548 , 17.05743971],
       [11.08193193, 11.55176136,  6.80536273],
       [15.89804   , 17.49440816, 13.04752743]])

In [30]:
arr1 / arr2

array([[24.57593342,  9.74683214, 48.10243143],
       [15.58465261,  2.8600858 , 25.38749902],
       [ 9.75229954, 18.48874166, 22.18444741]])

两个数组进行比较会生成布尔数组

In [31]:
arr1 = np.random.rand(9).reshape(3,3)
arr1

array([[0.62034266, 0.24751461, 0.59655297],
       [0.61522358, 0.81058655, 0.20314762],
       [0.51587834, 0.24778293, 0.69657439]])

In [32]:
arr2 = np.random.rand(9).reshape(3,3)
arr2

array([[0.67351524, 0.1219465 , 0.08181661],
       [0.60830724, 0.84849423, 0.2957092 ],
       [0.78192348, 0.08035438, 0.99959849]])

In [33]:
arr1 > arr2

array([[False,  True,  True],
       [ True, False, False],
       [False,  True, False]])

shape属性表示数组的形状
ndim属性表示数组的维度

In [34]:
print(arr1.shape)
print(arr1.ndim)

(3, 3)
2


In [35]:
arr1 = np.arange(3)
print(arr1.shape)
print(arr1.ndim)

(3,)
1


In [36]:
arr1 = np.array([[1,2,3]])
print(arr1.shape)
print(arr1.ndim)

(1, 3)
2


In [37]:
arr1 = np.array([[1],[2],[3]])
print(arr1.shape)
print(arr1.ndim)

(3, 1)
2


dtype属性表示数组的数据类型

In [38]:
arr = np.arange(9).reshape(3,3)
arr.dtype

dtype('int32')

In [39]:
arr = np.random.rand(3,3)
arr.dtype

dtype('float64')

In [40]:
arr = np.array([['helloo','world'],['this','is']])
arr.dtype

dtype('<U6')

In [41]:
arr = np.array([True,False,True,True])
arr.dtype

dtype('bool')

使用astype方法进行数据类型转换

In [42]:
arr = np.array([True,False,True,True]).astype(int)
print(arr)
print(arr.dtype)

[1 0 1 1]
int32


In [43]:
arr = arr.astype(float)
print(arr)
print(arr.dtype)

[1. 0. 1. 1.]
float64


计算次方和开方

In [44]:
arr = np.arange(4)
print(arr**2)
print(np.power(arr,2))
print(np.square(arr))

[0 1 4 9]
[0 1 4 9]
[0 1 4 9]


In [45]:
print(arr**0.5)
print(np.power(arr,0.5))
print(np.sqrt(arr))

[0.         1.         1.41421356 1.73205081]
[0.         1.         1.41421356 1.73205081]
[0.         1.         1.41421356 1.73205081]


数组的索引

In [46]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [47]:
arr[2]

array([6, 7, 8])

In [48]:
arr[2][1]

7

In [49]:
arr[2,1]

7

数组的切片，包含冒号左边的数字，不包含右边的数字。

In [50]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [51]:
arr[0:1]

array([[0, 1, 2]])

In [52]:
arr[1:3]

array([[3, 4, 5],
       [6, 7, 8]])

In [53]:
arr[0:2,1:3]

array([[1, 2],
       [4, 5]])

对切片的修改，会反映到原始数组上

In [54]:
arr[0:1,2] = 4
arr

array([[0, 1, 4],
       [3, 4, 5],
       [6, 7, 8]])