In [74]:
import numpy as np

使用np.arange()生成整数递增序列

In [75]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
# 包含1，不包含10，步长为2
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

%time 计算代码执行时间，代码只执行一次，并且需要放在一行

In [77]:
arr = np.arange(10000)
%time for i in range(10000): arr**2

Wall time: 115 ms


%timeit 计算代码执行的时间，代码会重复执行多次并计算平均值，并且需要放在一行

In [78]:
# for循环冒号后面不换行也是可以的
%timeit for i in range(10000): arr*2

90.3 ms ± 755 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


datetime.datatime.now()获取程序开始和结束的时间

In [79]:
import datetime
start = datetime.datetime.now()
arr = np.arange(10000)
for i in range(10000):
    arr**2
end = datetime.datetime.now()
print('start time:{}'.format(start))
print('end time:{}'.format(end))
print(end - start)

start time:2020-01-02 23:33:08.736882
end time:2020-01-02 23:33:08.837929
0:00:00.101047


time.time()获取程序开始和结束的时间

In [80]:
import time
import datetime
start = time.time()
arr = np.arange(10000)
for i in range(10000):
    arr**2
end = time.time()
print('start time:{}'.format(start))
print('end time:{}'.format(end))
print(end - start)

start time:1577979188.8479257
end time:1577979188.949937
0.10201144218444824


timeit.timeit('',number=10000)计算''之间代码执行的时间

In [81]:
import timeit
timeit.timeit('arr = [1,2,3,4]',number=10000)

0.0015087000001585693

生成ndarray对象的方式有哪些？  
np.array()  
np.zeros()  
np.ones()  
np.arange()  
np.random.randint()  
np.random.randn()  
np.random.rand()  
np.random.random()  

In [82]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [83]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [84]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [85]:
np.ones(3)

array([1., 1., 1.])

In [86]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [87]:
# 第一个参数表示开始值，第二个参数表示结束值（不包含），第三个参数表示矩阵的shape
np.random.randint(2,5,3)

array([2, 4, 4])

In [88]:
np.random.randint(1,10,(2,3))

array([[1, 8, 7],
       [9, 7, 7]])

In [89]:
# 标准正态分布随机数
np.random.randn(2,3)

array([[ 1.96002316,  2.12477725, -0.93732721],
       [ 0.90868561,  0.67761536, -0.03365578]])

In [90]:
# 0-1之间随机分布数
np.random.rand(2,3)

array([[0.14234635, 0.89169644, 0.19301945],
       [0.21304476, 0.3145565 , 0.57985746]])

In [91]:
# # 0-1之间随机分布数
np.random.random((2,3))

array([[0.95376892, 0.07652341, 0.54031317],
       [0.71169445, 0.69063482, 0.49682717]])

reshape方法用于转换矩阵的形状

In [92]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [93]:
# 生成二维数组，列为1
arr = np.arange(9).reshape(-1,1)
print(arr.shape)
print(arr)

(9, 1)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [94]:
# 生成二维数组，行为1
arr = np.arange(9).reshape(1,-1)
print(arr.shape)
print(arr)

(1, 9)
[[0 1 2 3 4 5 6 7 8]]


reshape(-1,n)将原数组转换成列为n的数组，行自行计算。数组元素的个数需要能够被n整除。

In [95]:
arr = np.arange(12).reshape(-1,3)
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

reshape(n,-1)将原数组转换成行为n的数组，列自行计算。数组元素的个数需要能够被n整除。

In [96]:
arr = np.arange(12).reshape(3,-1)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

ndarray对象之间进行加减乘除的规则

In [97]:
arr1 = np.random.randint(1,20,9).reshape(3,3)
arr1

array([[ 5,  2, 15],
       [ 9,  3,  1],
       [13,  5,  1]])

In [98]:
arr1 + 1

array([[ 6,  3, 16],
       [10,  4,  2],
       [14,  6,  2]])

In [99]:
arr1 * 2

array([[10,  4, 30],
       [18,  6,  2],
       [26, 10,  2]])

In [100]:
arr2 = np.random.rand(9).reshape(3,3)
arr2

array([[0.51550695, 0.01067869, 0.24970305],
       [0.30064127, 0.59247556, 0.60348812],
       [0.85505431, 0.60661854, 0.24906549]])

In [101]:
arr1 + arr2

array([[ 5.51550695,  2.01067869, 15.24970305],
       [ 9.30064127,  3.59247556,  1.60348812],
       [13.85505431,  5.60661854,  1.24906549]])

In [102]:
arr1 - arr2

array([[ 4.48449305,  1.98932131, 14.75029695],
       [ 8.69935873,  2.40752444,  0.39651188],
       [12.14494569,  4.39338146,  0.75093451]])

两个数组相同位置的元素进行相乘

In [103]:
arr1 = np.random.rand(3,3)
arr2 = np.random.rand(3,3)

In [104]:
arr1

array([[0.00871653, 0.79013964, 0.18829556],
       [0.49187002, 0.10082879, 0.03844468],
       [0.59803197, 0.76786498, 0.35041372]])

In [105]:
arr2

array([[0.20496231, 0.2075466 , 0.54886641],
       [0.79657726, 0.05986532, 0.46422339],
       [0.54170746, 0.75325935, 0.3131667 ]])

In [106]:
arr1 * arr2

array([[0.00178656, 0.16399079, 0.10334911],
       [0.39181247, 0.00603615, 0.01784692],
       [0.32395838, 0.57840148, 0.10973791]])

计算两个矩阵的点积（内积）

In [107]:
# 点乘，arr1的列数等于arr2的行数
arr1.dot(arr2)

array([[0.73319495, 0.19094645, 0.43055342],
       [0.20195851, 0.13708091, 0.32881761],
       [0.92405953, 0.4340404 , 0.79443845]])

In [108]:
np.dot(arr1,arr2)

array([[0.73319495, 0.19094645, 0.43055342],
       [0.20195851, 0.13708091, 0.32881761],
       [0.92405953, 0.4340404 , 0.79443845]])

In [109]:
arr1 / arr2

array([[0.04252749, 3.807047  , 0.34306265],
       [0.61747936, 1.68426039, 0.08281504],
       [1.10397588, 1.0193899 , 1.11893675]])

两个数组进行比较会生成布尔数组

In [110]:
arr1 = np.random.rand(9).reshape(3,3)
arr1

array([[0.04255613, 0.42543031, 0.84268481],
       [0.9270693 , 0.80085567, 0.58529314],
       [0.06358347, 0.31008494, 0.99723598]])

In [111]:
arr2 = np.random.rand(9).reshape(3,3)
arr2

array([[0.65815551, 0.73965507, 0.67366112],
       [0.09439792, 0.14206593, 0.78343069],
       [0.5888146 , 0.78543315, 0.81928717]])

In [112]:
arr1 > arr2

array([[False, False,  True],
       [ True,  True, False],
       [False, False,  True]])

shape属性表示数组的形状
ndim属性表示数组的维度

In [113]:
print(arr1.shape)
print(arr1.ndim)

(3, 3)
2


In [114]:
arr1 = np.arange(3)
print(arr1.shape)
print(arr1.ndim)

(3,)
1


In [115]:
arr1 = np.array([[1,2,3]])
print(arr1.shape)
print(arr1.ndim)

(1, 3)
2


In [116]:
arr1 = np.array([[1],[2],[3]])
print(arr1.shape)
print(arr1.ndim)

(3, 1)
2


dtype属性表示数组的数据类型

In [117]:
arr = np.arange(9).reshape(3,3)
arr.dtype

dtype('int32')

In [118]:
arr = np.random.rand(3,3)
arr.dtype

dtype('float64')

In [119]:
arr = np.array([['helloo','world'],['this','is']])
arr.dtype

dtype('<U6')

In [120]:
arr = np.array([True,False,True,True])
arr.dtype

dtype('bool')

使用astype方法进行数据类型转换

In [121]:
arr = np.array([True,False,True,True]).astype(int)
print(arr)
print(arr.dtype)

[1 0 1 1]
int32


In [122]:
arr = arr.astype(float)
print(arr)
print(arr.dtype)

[1. 0. 1. 1.]
float64


计算次方和开方

In [123]:
arr = np.arange(4)
print(arr**2)
print(np.power(arr,2))
print(np.square(arr))

[0 1 4 9]
[0 1 4 9]
[0 1 4 9]


In [124]:
print(arr**0.5)
print(np.power(arr,0.5))
print(np.sqrt(arr))

[0.         1.         1.41421356 1.73205081]
[0.         1.         1.41421356 1.73205081]
[0.         1.         1.41421356 1.73205081]


数组的索引

In [125]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [126]:
arr[2]

array([6, 7, 8])

In [127]:
arr[2][1]

7

In [128]:
arr[2,1]

7

数组的切片，包含冒号左边的数字，不包含右边的数字。

In [129]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [130]:
arr[0:1]

array([[0, 1, 2]])

In [131]:
arr[1:3]

array([[3, 4, 5],
       [6, 7, 8]])

In [132]:
arr[0:2,1:3]

array([[1, 2],
       [4, 5]])

对切片的修改，会反映到原始数组上

In [133]:
arr[0:1,2] = 4
arr

array([[0, 1, 4],
       [3, 4, 5],
       [6, 7, 8]])

使用copy()方法进行复制，再进行修改，则不影响原始数组

In [134]:
arr1 = arr[0:1].copy()
arr1

array([[0, 1, 4]])

In [135]:
arr1[0,1] = 2
arr1

array([[0, 2, 4]])

In [136]:
arr

array([[0, 1, 4],
       [3, 4, 5],
       [6, 7, 8]])

什么是切片索引？将切片与索引同时使用，可以得到低纬度的数组。

In [137]:
arr[0:2,2]

array([4, 5])

如何使用布尔索引？

In [138]:
arr = np.random.randint(1,100,(4,3))
arr

array([[49, 85, 61],
       [39, 84, 35],
       [ 3, 22, 30],
       [45, 18, 83]])

In [139]:
arr[:,2] > 30

array([ True,  True, False,  True])

In [140]:
arr[arr[:,2] > 30]

array([[49, 85, 61],
       [39, 84, 35],
       [45, 18, 83]])

In [141]:
arr[2,:] > 30

array([False, False, False])

In [142]:
arr[:,arr[2,:] > 30]

array([], shape=(4, 0), dtype=int32)

如何使用神奇索引？  
所谓的神奇索引，就是使用整数列表来对原数组进行排序。

In [143]:
arr

array([[49, 85, 61],
       [39, 84, 35],
       [ 3, 22, 30],
       [45, 18, 83]])

In [144]:
arr[[2,1,0,3]]

array([[ 3, 22, 30],
       [39, 84, 35],
       [49, 85, 61],
       [45, 18, 83]])

In [145]:
arr[:,[2,1,0]]

array([[61, 85, 49],
       [35, 84, 39],
       [30, 22,  3],
       [83, 18, 45]])

In [146]:
arr

array([[49, 85, 61],
       [39, 84, 35],
       [ 3, 22, 30],
       [45, 18, 83]])

数组的转置

In [147]:
arr.T

array([[49, 39,  3, 45],
       [85, 84, 22, 18],
       [61, 35, 30, 83]])

常用的一元通用函数

In [148]:
arr

array([[49, 85, 61],
       [39, 84, 35],
       [ 3, 22, 30],
       [45, 18, 83]])

In [149]:
# 求平方根
np.sqrt(arr)

array([[7.        , 9.21954446, 7.81024968],
       [6.244998  , 9.16515139, 5.91607978],
       [1.73205081, 4.69041576, 5.47722558],
       [6.70820393, 4.24264069, 9.11043358]])

In [150]:
# 求平方
np.square(arr)

array([[2401, 7225, 3721],
       [1521, 7056, 1225],
       [   9,  484,  900],
       [2025,  324, 6889]], dtype=int32)

In [151]:
# 求e为底的结果
np.exp(arr)

array([[1.90734657e+21, 8.22301271e+36, 3.10429794e+26],
       [8.65934004e+16, 3.02507732e+36, 1.58601345e+15],
       [2.00855369e+01, 3.58491285e+09, 1.06864746e+13],
       [3.49342711e+19, 6.56599691e+07, 1.11286375e+36]])

In [152]:
arr = arr * -1
arr

array([[-49, -85, -61],
       [-39, -84, -35],
       [ -3, -22, -30],
       [-45, -18, -83]])

求绝对值

In [153]:
np.abs(arr)

array([[49, 85, 61],
       [39, 84, 35],
       [ 3, 22, 30],
       [45, 18, 83]])

In [154]:
np.fabs(arr)

array([[49., 85., 61.],
       [39., 84., 35.],
       [ 3., 22., 30.],
       [45., 18., 83.]])

In [155]:
# np.modf()返回小数部分和整数部分
arr = np.random.rand(3,3)
arr

array([[0.87078961, 0.09591201, 0.4528296 ],
       [0.82717317, 0.87639479, 0.48981592],
       [0.86841391, 0.70356131, 0.89510747]])

In [156]:
arr = arr * 3
arr

array([[2.61236884, 0.28773602, 1.35848879],
       [2.48151952, 2.62918438, 1.46944776],
       [2.60524173, 2.11068393, 2.68532241]])

In [157]:
# 返回小数部分和整数部分
np.modf(arr)

(array([[0.61236884, 0.28773602, 0.35848879],
        [0.48151952, 0.62918438, 0.46944776],
        [0.60524173, 0.11068393, 0.68532241]]), array([[2., 0., 1.],
        [2., 2., 1.],
        [2., 2., 2.]]))

In [158]:
a,b = np.modf(arr)

In [159]:
print(a)
print(b)

[[0.61236884 0.28773602 0.35848879]
 [0.48151952 0.62918438 0.46944776]
 [0.60524173 0.11068393 0.68532241]]
[[2. 0. 1.]
 [2. 2. 1.]
 [2. 2. 2.]]


常用的二元通用函数

In [160]:
#返回两个数组求和的结果
np.add(arr1,arr2)

array([[0.65815551, 2.73965507, 4.67366112],
       [0.09439792, 2.14206593, 4.78343069],
       [0.5888146 , 2.78543315, 4.81928717]])

In [161]:
# 求每个元素的平方
np.power(arr,2)

array([[6.82447097, 0.08279202, 1.84549179],
       [6.15793914, 6.91261051, 2.15927671],
       [6.78728446, 4.45498667, 7.21095644]])

In [162]:
# 返回两个数组每个位置较大的元素
np.maximum(arr1,arr2)

array([[0.65815551, 2.        , 4.        ],
       [0.09439792, 2.        , 4.        ],
       [0.5888146 , 2.        , 4.        ]])

In [163]:
# 使用meshgrid()方法生成坐标矩阵
arr = np.arange(-5,5)
arr

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [164]:
xs,ys = np.meshgrid(arr,arr)

In [165]:
xs

array([[-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4],
       [-5, -4, -3, -2, -1,  0,  1,  2,  3,  4]])

In [166]:
ys

array([[-5, -5, -5, -5, -5, -5, -5, -5, -5, -5],
       [-4, -4, -4, -4, -4, -4, -4, -4, -4, -4],
       [-3, -3, -3, -3, -3, -3, -3, -3, -3, -3],
       [-2, -2, -2, -2, -2, -2, -2, -2, -2, -2],
       [-1, -1, -1, -1, -1, -1, -1, -1, -1, -1],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 1,  1,  1,  1,  1,  1,  1,  1,  1,  1],
       [ 2,  2,  2,  2,  2,  2,  2,  2,  2,  2],
       [ 3,  3,  3,  3,  3,  3,  3,  3,  3,  3],
       [ 4,  4,  4,  4,  4,  4,  4,  4,  4,  4]])

np.where(判断条件，真时的值，假时的值)

In [167]:
arr

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4])

In [168]:
arr = arr.reshape(2,5)

In [169]:
arr

array([[-5, -4, -3, -2, -1],
       [ 0,  1,  2,  3,  4]])

In [170]:
np.where(arr>0,1,-1)

array([[-1, -1, -1, -1, -1],
       [-1,  1,  1,  1,  1]])

In [171]:
arr2 = np.random.rand(2,5)
arr2

array([[0.18726563, 0.12892044, 0.84108836, 0.31706345, 0.25423327],
       [0.16883686, 0.00299046, 0.0361009 , 0.31555738, 0.13137155]])

In [172]:
np.where(arr>0,1,arr2)

array([[0.18726563, 0.12892044, 0.84108836, 0.31706345, 0.25423327],
       [0.16883686, 1.        , 1.        , 1.        , 1.        ]])

描述性统计方法

In [173]:
arr1

array([[0, 2, 4]])

In [174]:
arr1.sum()

6

In [175]:
np.sum(arr1)

6

In [176]:
np.mean(arr1)

2.0

In [177]:
arr1.mean()

2.0

In [178]:
np.std(arr1)

1.632993161855452

In [179]:
arr1.std()

1.632993161855452

In [180]:
np.var(arr1)

2.6666666666666665

In [181]:
arr1.var()

2.6666666666666665

In [182]:
# 计算累计和
np.cumsum(arr1)

array([0, 2, 6], dtype=int32)

In [183]:
arr1.cumsum()

array([0, 2, 6], dtype=int32)

In [184]:
# 计算累计积
np.cumprod(arr1)

array([0, 0, 0], dtype=int32)

In [185]:
arr1.cumprod()

array([0, 0, 0], dtype=int32)

In [186]:
print(np.min(arr1))
print(arr1.min())

0
0


In [187]:
print(np.max(arr1))
print(arr1.max())

4
4


In [188]:
# 最小值的位置
print(np.argmin(arr1))
print(arr1.argmin())

0
0


In [189]:
# 最大值的位置
print(np.argmax(arr1))
print(arr1.argmax())

2
2
